<?php declare(strict_types=1); namespace Tests;
use App\Controllers\SeriesSeasonController;use App\Core\{Auth,Csrf,Request,Session,View};use App\Integrations\Tmdb\{TmdbCatalog,TmdbEpisode,TmdbException,TmdbImageConfiguration,TmdbMediaDetails,TmdbSeasonDetails};use App\Media\{UserMediaItem,UserMediaPage,UserMediaStore,UserSeriesProgressStore};use PHPUnit\Framework\TestCase;
final class SeriesSeasonControllerTest extends TestCase {protected function setUp():void{$_SESSION=[];}
 public function testPublicPageRendersEpisodesEscapedAndLoginCta():void{[$c]=$this->fixture(false,false);$r=$c->show('1396','1');self::assertSame(200,$r->status());self::assertStringContainsString('Piloto',$r->body());self::assertStringContainsString('Entre para acompanhar',$r->body());self::assertStringNotContainsString('<script>alert(1)</script>',$r->body());self::assertStringContainsString('&lt;script&gt;alert(1)&lt;/script&gt;',$r->body());}
 public function testAuthenticatedOutsideListCannotMutate():void{[$c,$m,$p,$t,$csrf]=$this->fixture(true,false);$r=$c->mark(new Request(parsedBody:['_token'=>$csrf->token()]),'1396','1','1');self::assertSame(409,$r->status());self::assertSame([],$p->calls);}
 public function testMarkValidatesTmdbButUnmarkAndClearAreLocal():void{[$c,$m,$p,$t,$csrf]=$this->fixture(true,true);$token=$csrf->token();self::assertSame(303,$c->mark(new Request(parsedBody:['_token'=>$token]),'1396','1','1')->status());self::assertContains(['mark',7,1396,1,1],$p->calls);self::assertContains(['season',1396,1],$t->calls);$t->fail=true;$t->calls=[];self::assertSame(303,$c->unmark(new Request(parsedBody:['_token'=>$token]),'1396','1','1')->status());self::assertSame([], $t->calls);self::assertSame(303,$c->clearSeason(new Request(parsedBody:['_token'=>$token]),'1396','1')->status());self::assertSame([], $t->calls);self::assertSame(0,$m->statusUpdates);}
 public function testBulkUsesServerEpisodeNumbersAndCsrfBlocksWrites():void{[$c,$m,$p,$t,$csrf]=$this->fixture(true,true);self::assertSame(403,$c->markSeason(new Request(),'1396','1')->status());self::assertSame([],$p->calls);self::assertSame(303,$c->markSeason(new Request(parsedBody:['_token'=>$csrf->token()]),'1396','1')->status());self::assertSame([1,2],$p->bulk);}
 public function testInvalidAndUnknownEpisodeAreRejected():void{[$c,$m,$p,$t,$csrf]=$this->fixture(true,true);$r=new Request(parsedBody:['_token'=>$csrf->token()]);self::assertSame(404,$c->mark($r,'1396','-1','1')->status());self::assertSame(404,$c->mark($r,'1396','1','999')->status());self::assertSame([],$p->calls);}
 private function fixture(bool$logged,bool$listed):array{$s=new Session(false);$a=new Auth($s);if($logged)$a->login(7);$csrf=new Csrf($s);$m=new SeasonMediaStore($listed);$p=new SeasonProgressStore();$t=new SeasonCatalog();return[new SeriesSeasonController(new View(dirname(__DIR__).'/resources/views'),$t,$a,$csrf,$s,$m,$p),$m,$p,$t,$csrf];}}
final class SeasonMediaStore implements UserMediaStore {public int$statusUpdates=0;public function __construct(private bool$listed){}public function findForUser(int$u,string$s,string$t,int$i):?UserMediaItem{return$this->listed?new UserMediaItem(1,$u,$s,$t,$i,'watching','Breaking Bad',null,null,null,null,'',''):null;}public function create(int$u,TmdbMediaDetails$d,string$s):bool{return true;}public function updateStatus(int$u,string$s,string$t,int$i,string$x):bool{$this->statusUpdates++;return true;}public function delete(int$u,string$s,string$t,int$i):bool{return true;}public function paginateForUser(int$u,?string$s,?string$t,int$p,int$l):UserMediaPage{return new UserMediaPage([],0,1,$l);}public function countForUser(int$u):int{return 0;}}
final class SeasonProgressStore implements UserSeriesProgressStore {public array$calls=[];public array$bulk=[];public function watchedEpisodeNumbersForSeason(int$u,string$s,int$i,int$n):array{return[1];}public function countsBySeason(int$u,string$s,int$i):array{return[1=>1];}public function countForSeries(int$u,string$s,int$i):int{return 1;}public function markWatched(int$u,string$s,int$i,int$n,int$e):void{$this->calls[]=['mark',$u,$i,$n,$e];}public function unmarkWatched(int$u,string$s,int$i,int$n,int$e):void{$this->calls[]=['unmark',$u,$i,$n,$e];}public function markSeasonWatched(int$u,string$s,int$i,int$n,array$e):void{$this->bulk=$e;$this->calls[]=['bulk'];}public function clearSeason(int$u,string$s,int$i,int$n):void{$this->calls[]=['clear'];}}
final class SeasonCatalog implements TmdbCatalog {public array$calls=[];public bool$fail=false;public function configured():bool{return true;}public function configuration():TmdbImageConfiguration{throw new TmdbException('transport');}public function movieDetails(int$id):TmdbMediaDetails{throw new \LogicException();}public function seriesDetails(int$id):TmdbMediaDetails{throw new \LogicException();}public function seasonDetails(int$i,int$n):TmdbSeasonDetails{$this->calls[]=['season',$i,$n];if($this->fail)throw new TmdbException('transport');return new TmdbSeasonDetails('tmdb',$i,1,$n,'Temporada <script>alert(1)</script>','Resumo','2008-01-20',null,[new TmdbEpisode(1,$n,1,'Piloto','Resumo','2008-01-20',58,null),new TmdbEpisode(2,$n,2,'Segundo','Resumo','2999-01-01',48,null)]);}public function searchMovies(string$q,int$p=1):array{return[];}public function searchSeries(string$q,int$p=1):array{return[];}}
